#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
AGENTS_SRC="$SCRIPT_DIR/agents"
SKILLS_SRC="$SCRIPT_DIR/skills"
DEPLOY_DIR="$HOME/.ai-agency"
AGENTS_DST="$DEPLOY_DIR/agents"
REGISTRY_FILE="$AGENTS_DST/registry.yaml"

IDE=""
DRY_RUN=false
UPDATE_REGISTRY_ONLY=false
UNINSTALL=false

usage() {
  cat <<'EOF'
Usage:
  ./init.sh --ide <claude|cursor|codex|all> [--dry-run]
  ./init.sh --update-registry [--dry-run]
  ./init.sh --uninstall

Options:
  --ide <name>          Target IDE: claude, cursor, codex, or all (required unless --update-registry)
  --update-registry     Regenerate registry.yaml without redeploying agents or skills
  --uninstall           Remove all deployed agents, skills, and registry from all IDEs
  --dry-run             Preview without writing
  -h, --help            Show help
EOF
}

# ── Argument parsing ──────────────────────────────────────────────

while [ "$#" -gt 0 ]; do
  case "$1" in
    --ide)
      IDE="${2:-}"
      shift 2
      ;;
    --update-registry)
      UPDATE_REGISTRY_ONLY=true
      shift
      ;;
    --uninstall)
      UNINSTALL=true
      shift
      ;;
    --dry-run)
      DRY_RUN=true
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage
      exit 1
      ;;
  esac
done

# ── Uninstall ─────────────────────────────────────────────────────

uninstall() {
  local targets=()

  [ -d "$DEPLOY_DIR" ] && targets+=("$DEPLOY_DIR")

  for pattern in "$HOME/.claude/skills/ai-agency-"* "$HOME/.cursor/skills/ai-agency-"* "$HOME/.agents/skills/ai-agency-"*; do
    [ -e "$pattern" ] && targets+=("$pattern")
  done

  if [ "${#targets[@]}" -eq 0 ]; then
    echo "Nothing to remove — ai-agency is not installed."
    exit 0
  fi

  echo "The following will be removed:"
  for t in "${targets[@]}"; do
    echo "  $t"
  done

  printf "Proceed? [y/N] "
  read -r confirm
  if [ "$confirm" != "y" ] && [ "$confirm" != "Y" ]; then
    echo "Aborted."
    exit 0
  fi

  for t in "${targets[@]}"; do
    rm -rf "$t"
    echo "Removed: $t"
  done

  echo "Uninstall complete."
}

if [ "$UNINSTALL" = true ]; then
  uninstall
  exit 0
fi

if [ "$UPDATE_REGISTRY_ONLY" = false ] && [ -z "$IDE" ]; then
  echo "--ide is required (unless using --update-registry)." >&2
  usage
  exit 1
fi

if [ -n "$IDE" ] && [ "$IDE" != "claude" ] && [ "$IDE" != "cursor" ] && [ "$IDE" != "codex" ] && [ "$IDE" != "all" ]; then
  echo "Unsupported --ide value: $IDE (expected: claude, cursor, codex, or all)" >&2
  exit 1
fi

# ── Registry generation ──────────────────────────────────────────

generate_registry() {
  local agents_dir="$1"
  local output="$2"

  if [ "$DRY_RUN" = true ]; then
    echo "[dry-run] would generate registry: $output"
    return
  fi

  mkdir -p "$(dirname "$output")"

  cat > "$output" <<'HEADER'
# Auto-generated by init.sh — do not edit manually
agents:
HEADER

  local current_category=""

  # Find all .md agent files, sorted by path for stable output
  while read -r file; do
    local rel_path="${file#"$agents_dir"/}"
    local category
    category=$(dirname "$rel_path")
    local stem
    stem=$(basename "$rel_path" .md)

    # Extract name and description from YAML frontmatter
    local name="" description=""
    if head -1 "$file" | grep -q '^---$'; then
      name=$(awk '/^---$/{n++; next} n==1 && /^name:/{sub(/^name:[[:space:]]*/, ""); print; exit}' "$file")
      description=$(awk '/^---$/{n++; next} n==1 && /^description:/{sub(/^description:[[:space:]]*/, ""); print; exit}' "$file")
    fi

    # Fall back to stem if name is empty
    if [ -z "$name" ]; then
      name="$stem"
    fi

    # Write category header if new
    if [ "$category" != "$current_category" ]; then
      echo "  $category:" >> "$output"
      current_category="$category"
    fi

    echo "    - name: \"$name\"" >> "$output"
    if [ -n "$description" ]; then
      echo "      description: \"$description\"" >> "$output"
    fi
    echo "      file: $rel_path" >> "$output"
    echo "      stem: $stem" >> "$output"
  done < <(find "$agents_dir" -mindepth 2 -name '*.md' -not -name 'registry.yaml' | sort)

  echo "Generated registry: $output"
}

# ── Agent deployment ─────────────────────────────────────────────

deploy_agents() {
  if [ "$DRY_RUN" = true ]; then
    echo "[dry-run] would copy agents from $AGENTS_SRC/ → $AGENTS_DST/"
    return
  fi

  mkdir -p "$AGENTS_DST"

  # Copy each category directory
  for category_dir in "$AGENTS_SRC"/*/; do
    [ -d "$category_dir" ] || continue
    local category
    category=$(basename "$category_dir")
    local dst_category="$AGENTS_DST/$category"
    mkdir -p "$dst_category"

    for agent_file in "$category_dir"*.md; do
      [ -f "$agent_file" ] || continue
      local filename
      filename=$(basename "$agent_file")
      local dst_file="$dst_category/$filename"

      if [ -f "$dst_file" ] && diff -q "$agent_file" "$dst_file" >/dev/null 2>&1; then
        echo "Agent unchanged: $category/$filename"
        continue
      fi

      cp "$agent_file" "$dst_file"
      echo "Deployed agent: $category/$filename"
    done
  done
}

# ── Skills deployment ────────────────────────────────────────────

skills_dir_for_ide() {
  case "$1" in
    claude) echo "$HOME/.claude/skills" ;;
    cursor) echo "$HOME/.cursor/skills" ;;
    codex)  echo "$HOME/.agents/skills" ;;
  esac
}

deploy_skills() {
  local ide="$1"
  local target_base
  target_base=$(skills_dir_for_ide "$ide")

  for skill_dir in "$SKILLS_SRC"/*/; do
    [ -d "$skill_dir" ] || continue
    local name
    name=$(basename "$skill_dir")

    local src="$skill_dir/SKILL.md"
    [ -f "$src" ] || continue

    local dst="$target_base/$name/SKILL.md"

    if [ "$DRY_RUN" = true ]; then
      echo "[dry-run] would write skill: $dst"
      SKILLS_COUNT=$((SKILLS_COUNT + 1))
      continue
    fi

    if [ -f "$dst" ] && diff -q "$src" "$dst" >/dev/null 2>&1; then
      echo "Skill unchanged: $name ($ide)"
      SKILLS_COUNT=$((SKILLS_COUNT + 1))
      continue
    fi

    mkdir -p "$(dirname "$dst")"
    cp "$src" "$dst"
    echo "Wrote skill: $name → $dst"
    SKILLS_COUNT=$((SKILLS_COUNT + 1))
  done
}

# ── Main ─────────────────────────────────────────────────────────

if [ "$UPDATE_REGISTRY_ONLY" = true ]; then
  generate_registry "$AGENTS_DST" "$REGISTRY_FILE"
  echo "Done (registry update only)."
  exit 0
fi

# ── Untracked agent detection ────────────────────────────────────

detect_untracked_agents() {
  local untracked=()
  while read -r file; do
    local rel_path="${file#"$AGENTS_DST"/}"
    local src_file="$AGENTS_SRC/$rel_path"
    if [ ! -f "$src_file" ]; then
      untracked+=("$rel_path")
    fi
  done < <(find "$AGENTS_DST" -mindepth 2 -name '*.md' -not -name 'registry.yaml' | sort)

  if [ "${#untracked[@]}" -gt 0 ]; then
    echo ""
    echo "Untracked agents (in $AGENTS_DST but not in source):"
    for f in "${untracked[@]}"; do
      echo "  - $f"
    done
    echo "These files are not managed by the repo. Use --update-registry to include them in the registry."
  fi
}

# Full deploy
deploy_agents
generate_registry "$AGENTS_SRC" "$REGISTRY_FILE"
detect_untracked_agents

SKILLS_COUNT=0
if [ "$IDE" = "claude" ] || [ "$IDE" = "all" ]; then
  deploy_skills "claude"
fi
if [ "$IDE" = "codex" ] || [ "$IDE" = "all" ]; then
  deploy_skills "codex"
fi
if [ "$IDE" = "cursor" ] || [ "$IDE" = "all" ]; then
  deploy_skills "cursor"
fi

# Print deployment summary
agent_count=0
category_count=0
while read -r file; do
  agent_count=$((agent_count + 1))
done < <(find "$AGENTS_SRC" -mindepth 2 -name '*.md' | sort)
while read -r dir; do
  category_count=$((category_count + 1))
done < <(find "$AGENTS_SRC" -mindepth 1 -maxdepth 1 -type d | sort)

echo ""
echo "Deployed $agent_count agents across $category_count categories. $SKILLS_COUNT skills installed."
echo "Registry: $REGISTRY_FILE"
