#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
AGENTS_SRC="$SCRIPT_DIR/agents"
SKILLS_SRC="$SCRIPT_DIR/skills"
DEPLOY_DIR="$HOME/.ai-agency"
AGENTS_DST="$DEPLOY_DIR/agents"
REGISTRY_FILE="$AGENTS_DST/registry.yaml"

IDE=""
DRY_RUN=false
UPDATE_REGISTRY_ONLY=false

usage() {
  cat <<'EOF'
Usage:
  ./init.sh --ide <claude|cursor|codex|all> [--dry-run]
  ./init.sh --update-registry [--dry-run]

Options:
  --ide <name>          Target IDE: claude, cursor, codex, or all (required unless --update-registry)
  --update-registry     Regenerate registry.yaml without redeploying agents or skills
  --dry-run             Preview without writing
  -h, --help            Show help
EOF
}

# ── Argument parsing ──────────────────────────────────────────────

while [ "$#" -gt 0 ]; do
  case "$1" in
    --ide)
      IDE="${2:-}"
      shift 2
      ;;
    --update-registry)
      UPDATE_REGISTRY_ONLY=true
      shift
      ;;
    --dry-run)
      DRY_RUN=true
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage
      exit 1
      ;;
  esac
done

if [ "$UPDATE_REGISTRY_ONLY" = false ] && [ -z "$IDE" ]; then
  echo "--ide is required (unless using --update-registry)." >&2
  usage
  exit 1
fi

if [ -n "$IDE" ] && [ "$IDE" != "claude" ] && [ "$IDE" != "cursor" ] && [ "$IDE" != "codex" ] && [ "$IDE" != "all" ]; then
  echo "Unsupported --ide value: $IDE (expected: claude, cursor, codex, or all)" >&2
  exit 1
fi

# ── Registry generation ──────────────────────────────────────────

generate_registry() {
  local agents_dir="$1"
  local output="$2"

  if [ "$DRY_RUN" = true ]; then
    echo "[dry-run] would generate registry: $output"
    return
  fi

  mkdir -p "$(dirname "$output")"

  cat > "$output" <<'HEADER'
# Auto-generated by init.sh — do not edit manually
agents:
HEADER

  local current_category=""

  # Find all .md agent files, sorted by path for stable output
  find "$agents_dir" -mindepth 2 -name '*.md' -not -name 'registry.yaml' | sort | while read -r file; do
    local rel_path="${file#"$agents_dir"/}"
    local category
    category=$(dirname "$rel_path")
    local stem
    stem=$(basename "$rel_path" .md)

    # Extract name and description from YAML frontmatter
    local name="" description=""
    if head -1 "$file" | grep -q '^---$'; then
      name=$(awk '/^---$/{n++; next} n==1 && /^name:/{sub(/^name:[[:space:]]*/, ""); print; exit}' "$file")
      description=$(awk '/^---$/{n++; next} n==1 && /^description:/{sub(/^description:[[:space:]]*/, ""); print; exit}' "$file")
    fi

    # Fall back to stem if name is empty
    if [ -z "$name" ]; then
      name="$stem"
    fi

    # Write category header if new
    if [ "$category" != "$current_category" ]; then
      echo "  $category:" >> "$output"
      current_category="$category"
    fi

    echo "    - name: \"$name\"" >> "$output"
    if [ -n "$description" ]; then
      echo "      description: \"$description\"" >> "$output"
    fi
    echo "      file: $rel_path" >> "$output"
    echo "      stem: $stem" >> "$output"
  done

  echo "Generated registry: $output"
}

# ── Agent deployment ─────────────────────────────────────────────

deploy_agents() {
  if [ "$DRY_RUN" = true ]; then
    echo "[dry-run] would copy agents from $AGENTS_SRC/ → $AGENTS_DST/"
    return
  fi

  mkdir -p "$AGENTS_DST"

  # Copy each category directory
  for category_dir in "$AGENTS_SRC"/*/; do
    [ -d "$category_dir" ] || continue
    local category
    category=$(basename "$category_dir")
    local dst_category="$AGENTS_DST/$category"
    mkdir -p "$dst_category"

    for agent_file in "$category_dir"*.md; do
      [ -f "$agent_file" ] || continue
      local filename
      filename=$(basename "$agent_file")
      local dst_file="$dst_category/$filename"

      if [ -f "$dst_file" ] && diff -q "$agent_file" "$dst_file" >/dev/null 2>&1; then
        echo "Agent unchanged: $category/$filename"
        continue
      fi

      cp "$agent_file" "$dst_file"
      echo "Deployed agent: $category/$filename"
    done
  done
}

# ── Skills deployment ────────────────────────────────────────────

skills_dir_for_ide() {
  case "$1" in
    claude) echo "$HOME/.claude/skills" ;;
    cursor) echo "$HOME/.cursor/skills" ;;
    codex)  echo "$HOME/.agents/skills" ;;
  esac
}

deploy_skills() {
  local ide="$1"
  local target_base
  target_base=$(skills_dir_for_ide "$ide")

  # Determine which skill variant subdirectory to use
  local variant_suffix=""
  if [ "$ide" = "cursor" ] || [ "$ide" = "codex" ]; then
    variant_suffix="-inline"
  fi

  for skill_dir in "$SKILLS_SRC"/*/; do
    [ -d "$skill_dir" ] || continue
    local name
    name=$(basename "$skill_dir")

    # Skip variant directories (they are deployed as part of the base skill)
    case "$name" in
      *-inline) continue ;;
    esac

    # Check if an IDE-specific variant exists
    local src
    if [ -n "$variant_suffix" ] && [ -d "$SKILLS_SRC/${name}${variant_suffix}" ]; then
      src="$SKILLS_SRC/${name}${variant_suffix}/SKILL.md"
    else
      src="$skill_dir/SKILL.md"
    fi

    [ -f "$src" ] || continue

    local dst="$target_base/$name/SKILL.md"

    if [ "$DRY_RUN" = true ]; then
      echo "[dry-run] would write skill: $dst"
      continue
    fi

    if [ -f "$dst" ] && diff -q "$src" "$dst" >/dev/null 2>&1; then
      echo "Skill unchanged: $name ($ide)"
      continue
    fi

    mkdir -p "$(dirname "$dst")"
    cp "$src" "$dst"
    echo "Wrote skill: $name → $dst"
  done
}

# ── Main ─────────────────────────────────────────────────────────

if [ "$UPDATE_REGISTRY_ONLY" = true ]; then
  generate_registry "$AGENTS_DST" "$REGISTRY_FILE"
  echo "Done (registry update only)."
  exit 0
fi

# Full deploy
deploy_agents
generate_registry "$AGENTS_DST" "$REGISTRY_FILE"

if [ "$IDE" = "claude" ] || [ "$IDE" = "all" ]; then
  deploy_skills "claude"
fi
if [ "$IDE" = "codex" ] || [ "$IDE" = "all" ]; then
  deploy_skills "codex"
fi
if [ "$IDE" = "cursor" ] || [ "$IDE" = "all" ]; then
  deploy_skills "cursor"
fi

echo "Done."
