#!/bin/sh
# Generate agency registry from source agent files.
# Called by ais after agents are deployed.
# Env: AIS_PLUGIN_SOURCE, AIS_DATA_DIR

mkdir -p "$AIS_DATA_DIR"

output="$AIS_DATA_DIR/registry.yaml"

printf '# Auto-generated by agency post-install — do not edit manually\nagents:\n' > "$output"

for agent_file in "$AIS_PLUGIN_SOURCE/agents/"*.md; do
  [ -f "$agent_file" ] || continue
  stem=$(basename "$agent_file" .md)
  name=$(awk '/^---$/{n++; next} n==1 && /^name:/{sub(/^name:[[:space:]]*/, ""); print; exit}' "$agent_file")
  description=$(awk '/^---$/{n++; next} n==1 && /^description:/{sub(/^description:[[:space:]]*/, ""); print; exit}' "$agent_file")
  [ -z "$name" ] && name="$stem"
  printf '  - name: "%s"\n' "$name" >> "$output"
  [ -n "$description" ] && printf '    description: "%s"\n' "$description" >> "$output"
  printf '    file: %s.md\n' "$stem" >> "$output"
  printf '    stem: %s\n' "$stem" >> "$output"
done

echo "Generated registry: $output"
